//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class PEDIMENTO
    {
        #region Primitive Properties
    
        public virtual long UNID_PEDIMENTO
        {
            get;
            set;
        }
    
        public virtual long UNID_LOTE
        {
            get { return _uNID_LOTE; }
            set
            {
                if (_uNID_LOTE != value)
                {
                    if (LOTE != null && LOTE.UNID_LOTE != value)
                    {
                        LOTE = null;
                    }
                    _uNID_LOTE = value;
                }
            }
        }
        private long _uNID_LOTE;
    
        public virtual long UNID_TIPO_PEDIMENTO
        {
            get { return _uNID_TIPO_PEDIMENTO; }
            set
            {
                if (_uNID_TIPO_PEDIMENTO != value)
                {
                    if (TIPO_PEDIMENTO != null && TIPO_PEDIMENTO.UNID_TIPO_PEDIMENTO != value)
                    {
                        TIPO_PEDIMENTO = null;
                    }
                    _uNID_TIPO_PEDIMENTO = value;
                }
            }
        }
        private long _uNID_TIPO_PEDIMENTO;
    
        public virtual string PEDIMENTO_NUMERO
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual TIPO_PEDIMENTO TIPO_PEDIMENTO
        {
            get { return _tIPO_PEDIMENTO; }
            set
            {
                if (!ReferenceEquals(_tIPO_PEDIMENTO, value))
                {
                    var previousValue = _tIPO_PEDIMENTO;
                    _tIPO_PEDIMENTO = value;
                    FixupTIPO_PEDIMENTO(previousValue);
                }
            }
        }
        private TIPO_PEDIMENTO _tIPO_PEDIMENTO;
    
        public virtual LOTE LOTE
        {
            get { return _lOTE; }
            set
            {
                if (!ReferenceEquals(_lOTE, value))
                {
                    var previousValue = _lOTE;
                    _lOTE = value;
                    FixupLOTE(previousValue);
                }
            }
        }
        private LOTE _lOTE;

        #endregion
        #region Association Fixup
    
        private void FixupTIPO_PEDIMENTO(TIPO_PEDIMENTO previousValue)
        {
            if (previousValue != null && previousValue.PEDIMENTOes.Contains(this))
            {
                previousValue.PEDIMENTOes.Remove(this);
            }
    
            if (TIPO_PEDIMENTO != null)
            {
                if (!TIPO_PEDIMENTO.PEDIMENTOes.Contains(this))
                {
                    TIPO_PEDIMENTO.PEDIMENTOes.Add(this);
                }
                if (UNID_TIPO_PEDIMENTO != TIPO_PEDIMENTO.UNID_TIPO_PEDIMENTO)
                {
                    UNID_TIPO_PEDIMENTO = TIPO_PEDIMENTO.UNID_TIPO_PEDIMENTO;
                }
            }
        }
    
        private void FixupLOTE(LOTE previousValue)
        {
            if (previousValue != null && previousValue.PEDIMENTOes.Contains(this))
            {
                previousValue.PEDIMENTOes.Remove(this);
            }
    
            if (LOTE != null)
            {
                if (!LOTE.PEDIMENTOes.Contains(this))
                {
                    LOTE.PEDIMENTOes.Add(this);
                }
                if (UNID_LOTE != LOTE.UNID_LOTE)
                {
                    UNID_LOTE = LOTE.UNID_LOTE;
                }
            }
        }

        #endregion
    }
}
