//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class STG_FACTURA_DETALLE
    {
        #region Primitive Properties
    
        public virtual Nullable<long> UNID_FACTURA_DETALLE
        {
            get;
            set;
        }
    
        public virtual string FACTURA_NUMERO
        {
            get;
            set;
        }
    
        public virtual string FECHA_FACTURA
        {
            get;
            set;
        }
    
        public virtual long UNID_PROVEEDOR
        {
            get;
            set;
        }
    
        public virtual string PROVEEDOR_NAME
        {
            get;
            set;
        }
    
        public virtual long UNID_MONEDA
        {
            get;
            set;
        }
    
        public virtual string MONEDA_NAME
        {
            get;
            set;
        }
    
        public virtual string NUMERO_PEDIMENTO
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IVA_POR
        {
            get;
            set;
        }
    
        public virtual Nullable<double> TC
        {
            get;
            set;
        }
    
        public virtual string CATEGORIA_NAME
        {
            get;
            set;
        }
    
        public virtual string MODELO_NAME
        {
            get;
            set;
        }
    
        public virtual string EQUIPO_NAME
        {
            get;
            set;
        }
    
        public virtual string MARCA_NAME
        {
            get;
            set;
        }
    
        public virtual long UNID_ARTICULO
        {
            get;
            set;
        }
    
        public virtual string ARTICULO_NAME
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CANTIDAD
        {
            get;
            set;
        }
    
        public virtual Nullable<double> PRECIO_UNITARIO
        {
            get;
            set;
        }
    
        public virtual long UNID_UNIDAD
        {
            get;
            set;
        }
    
        public virtual string UNIDAD_MEDIDA
        {
            get;
            set;
        }

        #endregion
    }
}
