//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class TECNICO
    {
        #region Primitive Properties
    
        public virtual long UNID_TECNICO
        {
            get;
            set;
        }
    
        public virtual string TECNICO_NAME
        {
            get;
            set;
        }
    
        public virtual string MAIL
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_CIUDAD
        {
            get { return _uNID_CIUDAD; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_CIUDAD != value)
                    {
                        if (CIUDAD != null && CIUDAD.UNID_CIUDAD != value)
                        {
                            CIUDAD = null;
                        }
                        _uNID_CIUDAD = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _uNID_CIUDAD;
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<MOVIMENTO> MOVIMENTOes
        {
            get
            {
                if (_mOVIMENTOes == null)
                {
                    var newCollection = new FixupCollection<MOVIMENTO>();
                    newCollection.CollectionChanged += FixupMOVIMENTOes;
                    _mOVIMENTOes = newCollection;
                }
                return _mOVIMENTOes;
            }
            set
            {
                if (!ReferenceEquals(_mOVIMENTOes, value))
                {
                    var previousValue = _mOVIMENTOes as FixupCollection<MOVIMENTO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMOVIMENTOes;
                    }
                    _mOVIMENTOes = value;
                    var newValue = value as FixupCollection<MOVIMENTO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMOVIMENTOes;
                    }
                }
            }
        }
        private ICollection<MOVIMENTO> _mOVIMENTOes;
    
        public virtual ICollection<MOVIMENTO> MOVIMENTOes1
        {
            get
            {
                if (_mOVIMENTOes1 == null)
                {
                    var newCollection = new FixupCollection<MOVIMENTO>();
                    newCollection.CollectionChanged += FixupMOVIMENTOes1;
                    _mOVIMENTOes1 = newCollection;
                }
                return _mOVIMENTOes1;
            }
            set
            {
                if (!ReferenceEquals(_mOVIMENTOes1, value))
                {
                    var previousValue = _mOVIMENTOes1 as FixupCollection<MOVIMENTO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMOVIMENTOes1;
                    }
                    _mOVIMENTOes1 = value;
                    var newValue = value as FixupCollection<MOVIMENTO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMOVIMENTOes1;
                    }
                }
            }
        }
        private ICollection<MOVIMENTO> _mOVIMENTOes1;
    
        public virtual CIUDAD CIUDAD
        {
            get { return _cIUDAD; }
            set
            {
                if (!ReferenceEquals(_cIUDAD, value))
                {
                    var previousValue = _cIUDAD;
                    _cIUDAD = value;
                    FixupCIUDAD(previousValue);
                }
            }
        }
        private CIUDAD _cIUDAD;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCIUDAD(CIUDAD previousValue)
        {
            if (previousValue != null && previousValue.TECNICOes.Contains(this))
            {
                previousValue.TECNICOes.Remove(this);
            }
    
            if (CIUDAD != null)
            {
                if (!CIUDAD.TECNICOes.Contains(this))
                {
                    CIUDAD.TECNICOes.Add(this);
                }
                if (UNID_CIUDAD != CIUDAD.UNID_CIUDAD)
                {
                    UNID_CIUDAD = CIUDAD.UNID_CIUDAD;
                }
            }
            else if (!_settingFK)
            {
                UNID_CIUDAD = null;
            }
        }
    
        private void FixupMOVIMENTOes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MOVIMENTO item in e.NewItems)
                {
                    item.TECNICO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MOVIMENTO item in e.OldItems)
                {
                    if (ReferenceEquals(item.TECNICO, this))
                    {
                        item.TECNICO = null;
                    }
                }
            }
        }
    
        private void FixupMOVIMENTOes1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MOVIMENTO item in e.NewItems)
                {
                    item.TECNICO1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MOVIMENTO item in e.OldItems)
                {
                    if (ReferenceEquals(item.TECNICO1, this))
                    {
                        item.TECNICO1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
