//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class TECNICO
    {
        #region Primitive Properties
    
        public virtual long UNID_TECNICO
        {
            get;
            set;
        }
    
        public virtual string TECNICO_NAME
        {
            get;
            set;
        }
    
        public virtual string MAIL
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_CIUDAD
        {
            get { return _uNID_CIUDAD; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_CIUDAD != value)
                    {
                        if (CIUDAD != null && CIUDAD.UNID_CIUDAD != value)
                        {
                            CIUDAD = null;
                        }
                        _uNID_CIUDAD = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _uNID_CIUDAD;
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CIUDAD CIUDAD
        {
            get { return _cIUDAD; }
            set
            {
                if (!ReferenceEquals(_cIUDAD, value))
                {
                    var previousValue = _cIUDAD;
                    _cIUDAD = value;
                    FixupCIUDAD(previousValue);
                }
            }
        }
        private CIUDAD _cIUDAD;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCIUDAD(CIUDAD previousValue)
        {
            if (previousValue != null && previousValue.TECNICOes.Contains(this))
            {
                previousValue.TECNICOes.Remove(this);
            }
    
            if (CIUDAD != null)
            {
                if (!CIUDAD.TECNICOes.Contains(this))
                {
                    CIUDAD.TECNICOes.Add(this);
                }
                if (UNID_CIUDAD != CIUDAD.UNID_CIUDAD)
                {
                    UNID_CIUDAD = CIUDAD.UNID_CIUDAD;
                }
            }
            else if (!_settingFK)
            {
                UNID_CIUDAD = null;
            }
        }

        #endregion
    }
}
