//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class TERMINO_ENVIO
    {
        #region Primitive Properties
    
        public virtual long UNID_TERMINO_ENVIO
        {
            get;
            set;
        }
    
        public virtual string CLAVE
        {
            get;
            set;
        }
    
        public virtual string TERMINO
        {
            get;
            set;
        }
    
        public virtual string SIGNIFICADO
        {
            get;
            set;
        }
    
        public virtual bool GENERA_LOTES
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }

        #endregion
    }
}
