//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class TIPO_PEDIMENTO
    {
        #region Primitive Properties
    
        public virtual long UNID_TIPO_PEDIMENTO
        {
            get;
            set;
        }
    
        public virtual string TIPO_PEDIMENTO_NAME
        {
            get;
            set;
        }
    
        public virtual string CLAVE
        {
            get;
            set;
        }
    
        public virtual string REGIMEN
        {
            get;
            set;
        }
    
        public virtual string NOTA
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<PEDIMENTO> PEDIMENTOes
        {
            get
            {
                if (_pEDIMENTOes == null)
                {
                    var newCollection = new FixupCollection<PEDIMENTO>();
                    newCollection.CollectionChanged += FixupPEDIMENTOes;
                    _pEDIMENTOes = newCollection;
                }
                return _pEDIMENTOes;
            }
            set
            {
                if (!ReferenceEquals(_pEDIMENTOes, value))
                {
                    var previousValue = _pEDIMENTOes as FixupCollection<PEDIMENTO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPEDIMENTOes;
                    }
                    _pEDIMENTOes = value;
                    var newValue = value as FixupCollection<PEDIMENTO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPEDIMENTOes;
                    }
                }
            }
        }
        private ICollection<PEDIMENTO> _pEDIMENTOes;

        #endregion
        #region Association Fixup
    
        private void FixupPEDIMENTOes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PEDIMENTO item in e.NewItems)
                {
                    item.TIPO_PEDIMENTO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PEDIMENTO item in e.OldItems)
                {
                    if (ReferenceEquals(item.TIPO_PEDIMENTO, this))
                    {
                        item.TIPO_PEDIMENTO = null;
                    }
                }
            }
        }

        #endregion
    }
}
