//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class UPLOAD_LOG
    {
        #region Primitive Properties
    
        public virtual long UNID_UPLOAD_LOG
        {
            get;
            set;
        }
    
        public virtual string MSG
        {
            get;
            set;
        }
    
        public virtual string IP_DIR
        {
            get;
            set;
        }
    
        public virtual string PC_NAME
        {
            get;
            set;
        }
    
        public virtual long UNID_USUARIO
        {
            get { return _uNID_USUARIO; }
            set
            {
                if (_uNID_USUARIO != value)
                {
                    if (USUARIO != null && USUARIO.UNID_USUARIO != value)
                    {
                        USUARIO = null;
                    }
                    _uNID_USUARIO = value;
                }
            }
        }
        private long _uNID_USUARIO;

        #endregion
        #region Navigation Properties
    
        public virtual USUARIO USUARIO
        {
            get { return _uSUARIO; }
            set
            {
                if (!ReferenceEquals(_uSUARIO, value))
                {
                    var previousValue = _uSUARIO;
                    _uSUARIO = value;
                    FixupUSUARIO(previousValue);
                }
            }
        }
        private USUARIO _uSUARIO;

        #endregion
        #region Association Fixup
    
        private void FixupUSUARIO(USUARIO previousValue)
        {
            if (previousValue != null && previousValue.UPLOAD_LOG.Contains(this))
            {
                previousValue.UPLOAD_LOG.Remove(this);
            }
    
            if (USUARIO != null)
            {
                if (!USUARIO.UPLOAD_LOG.Contains(this))
                {
                    USUARIO.UPLOAD_LOG.Add(this);
                }
                if (UNID_USUARIO != USUARIO.UNID_USUARIO)
                {
                    UNID_USUARIO = USUARIO.UNID_USUARIO;
                }
            }
        }

        #endregion
    }
}
