//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class BANCO
    {
        #region Primitive Properties
    
        public virtual long UNID_BANCO
        {
            get;
            set;
        }
    
        public virtual string BANCO_NAME
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<PROVEEDOR_CUENTA> PROVEEDOR_CUENTA
        {
            get
            {
                if (_pROVEEDOR_CUENTA == null)
                {
                    var newCollection = new FixupCollection<PROVEEDOR_CUENTA>();
                    newCollection.CollectionChanged += FixupPROVEEDOR_CUENTA;
                    _pROVEEDOR_CUENTA = newCollection;
                }
                return _pROVEEDOR_CUENTA;
            }
            set
            {
                if (!ReferenceEquals(_pROVEEDOR_CUENTA, value))
                {
                    var previousValue = _pROVEEDOR_CUENTA as FixupCollection<PROVEEDOR_CUENTA>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPROVEEDOR_CUENTA;
                    }
                    _pROVEEDOR_CUENTA = value;
                    var newValue = value as FixupCollection<PROVEEDOR_CUENTA>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPROVEEDOR_CUENTA;
                    }
                }
            }
        }
        private ICollection<PROVEEDOR_CUENTA> _pROVEEDOR_CUENTA;

        #endregion
        #region Association Fixup
    
        private void FixupPROVEEDOR_CUENTA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PROVEEDOR_CUENTA item in e.NewItems)
                {
                    item.BANCO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PROVEEDOR_CUENTA item in e.OldItems)
                {
                    if (ReferenceEquals(item.BANCO, this))
                    {
                        item.BANCO = null;
                    }
                }
            }
        }

        #endregion
    }
}
