//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class BATCH_LOAD_CARGAMVTOS
    {
        #region Primitive Properties
    
        public virtual int ID_BATCH
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> START_EXEC_DATE
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> END_EXEC_DATE
        {
            get;
            set;
        }

        #endregion
    }
}
