//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class MENU
    {
        #region Primitive Properties
    
        public virtual long UNID_MENU
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_MENU_PARENT
        {
            get { return _uNID_MENU_PARENT; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_MENU_PARENT != value)
                    {
                        if (MENU2 != null && MENU2.UNID_MENU != value)
                        {
                            MENU2 = null;
                        }
                        _uNID_MENU_PARENT = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _uNID_MENU_PARENT;
    
        public virtual string MENU_NAME
        {
            get;
            set;
        }
    
        public virtual bool IS_LEAF
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<MENU> MENU1
        {
            get
            {
                if (_mENU1 == null)
                {
                    var newCollection = new FixupCollection<MENU>();
                    newCollection.CollectionChanged += FixupMENU1;
                    _mENU1 = newCollection;
                }
                return _mENU1;
            }
            set
            {
                if (!ReferenceEquals(_mENU1, value))
                {
                    var previousValue = _mENU1 as FixupCollection<MENU>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMENU1;
                    }
                    _mENU1 = value;
                    var newValue = value as FixupCollection<MENU>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMENU1;
                    }
                }
            }
        }
        private ICollection<MENU> _mENU1;
    
        public virtual MENU MENU2
        {
            get { return _mENU2; }
            set
            {
                if (!ReferenceEquals(_mENU2, value))
                {
                    var previousValue = _mENU2;
                    _mENU2 = value;
                    FixupMENU2(previousValue);
                }
            }
        }
        private MENU _mENU2;
    
        public virtual ICollection<ROL_MENU> ROL_MENU
        {
            get
            {
                if (_rOL_MENU == null)
                {
                    var newCollection = new FixupCollection<ROL_MENU>();
                    newCollection.CollectionChanged += FixupROL_MENU;
                    _rOL_MENU = newCollection;
                }
                return _rOL_MENU;
            }
            set
            {
                if (!ReferenceEquals(_rOL_MENU, value))
                {
                    var previousValue = _rOL_MENU as FixupCollection<ROL_MENU>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupROL_MENU;
                    }
                    _rOL_MENU = value;
                    var newValue = value as FixupCollection<ROL_MENU>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupROL_MENU;
                    }
                }
            }
        }
        private ICollection<ROL_MENU> _rOL_MENU;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupMENU2(MENU previousValue)
        {
            if (previousValue != null && previousValue.MENU1.Contains(this))
            {
                previousValue.MENU1.Remove(this);
            }
    
            if (MENU2 != null)
            {
                if (!MENU2.MENU1.Contains(this))
                {
                    MENU2.MENU1.Add(this);
                }
                if (UNID_MENU_PARENT != MENU2.UNID_MENU)
                {
                    UNID_MENU_PARENT = MENU2.UNID_MENU;
                }
            }
            else if (!_settingFK)
            {
                UNID_MENU_PARENT = null;
            }
        }
    
        private void FixupMENU1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MENU item in e.NewItems)
                {
                    item.MENU2 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MENU item in e.OldItems)
                {
                    if (ReferenceEquals(item.MENU2, this))
                    {
                        item.MENU2 = null;
                    }
                }
            }
        }
    
        private void FixupROL_MENU(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ROL_MENU item in e.NewItems)
                {
                    item.MENU = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ROL_MENU item in e.OldItems)
                {
                    if (ReferenceEquals(item.MENU, this))
                    {
                        item.MENU = null;
                    }
                }
            }
        }

        #endregion
    }
}
