//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class PAI
    {
        #region Primitive Properties
    
        public virtual long UNID_PAIS
        {
            get;
            set;
        }
    
        public virtual string PAIS
        {
            get;
            set;
        }
    
        public virtual string ISO
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<PROVEEDOR> PROVEEDORs
        {
            get
            {
                if (_pROVEEDORs == null)
                {
                    var newCollection = new FixupCollection<PROVEEDOR>();
                    newCollection.CollectionChanged += FixupPROVEEDORs;
                    _pROVEEDORs = newCollection;
                }
                return _pROVEEDORs;
            }
            set
            {
                if (!ReferenceEquals(_pROVEEDORs, value))
                {
                    var previousValue = _pROVEEDORs as FixupCollection<PROVEEDOR>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPROVEEDORs;
                    }
                    _pROVEEDORs = value;
                    var newValue = value as FixupCollection<PROVEEDOR>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPROVEEDORs;
                    }
                }
            }
        }
        private ICollection<PROVEEDOR> _pROVEEDORs;

        #endregion
        #region Association Fixup
    
        private void FixupPROVEEDORs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PROVEEDOR item in e.NewItems)
                {
                    item.PAI = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PROVEEDOR item in e.OldItems)
                {
                    if (ReferenceEquals(item.PAI, this))
                    {
                        item.PAI = null;
                    }
                }
            }
        }

        #endregion
    }
}
