//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class PROPIEDAD
    {
        #region Primitive Properties
    
        public virtual long UNID_PROPIEDAD
        {
            get;
            set;
        }
    
        public virtual string PROPIEDAD1
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<ITEM> ITEMs
        {
            get
            {
                if (_iTEMs == null)
                {
                    var newCollection = new FixupCollection<ITEM>();
                    newCollection.CollectionChanged += FixupITEMs;
                    _iTEMs = newCollection;
                }
                return _iTEMs;
            }
            set
            {
                if (!ReferenceEquals(_iTEMs, value))
                {
                    var previousValue = _iTEMs as FixupCollection<ITEM>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupITEMs;
                    }
                    _iTEMs = value;
                    var newValue = value as FixupCollection<ITEM>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupITEMs;
                    }
                }
            }
        }
        private ICollection<ITEM> _iTEMs;

        #endregion
        #region Association Fixup
    
        private void FixupITEMs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ITEM item in e.NewItems)
                {
                    item.PROPIEDAD = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ITEM item in e.OldItems)
                {
                    if (ReferenceEquals(item.PROPIEDAD, this))
                    {
                        item.PROPIEDAD = null;
                    }
                }
            }
        }

        #endregion
    }
}
