//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class PROVEEDOR_CUENTA
    {
        #region Primitive Properties
    
        public virtual long UNID_PROVEEDOR
        {
            get { return _uNID_PROVEEDOR; }
            set
            {
                if (_uNID_PROVEEDOR != value)
                {
                    if (PROVEEDOR != null && PROVEEDOR.UNID_PROVEEDOR != value)
                    {
                        PROVEEDOR = null;
                    }
                    _uNID_PROVEEDOR = value;
                }
            }
        }
        private long _uNID_PROVEEDOR;
    
        public virtual long UNID_PROVEEDOR_CUENTA
        {
            get;
            set;
        }
    
        public virtual long UNID_BANCO
        {
            get { return _uNID_BANCO; }
            set
            {
                if (_uNID_BANCO != value)
                {
                    if (BANCO != null && BANCO.UNID_BANCO != value)
                    {
                        BANCO = null;
                    }
                    _uNID_BANCO = value;
                }
            }
        }
        private long _uNID_BANCO;
    
        public virtual string NUMERO_CUENTA
        {
            get;
            set;
        }
    
        public virtual string CLABE
        {
            get;
            set;
        }
    
        public virtual string BENEFICIARIO
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual BANCO BANCO
        {
            get { return _bANCO; }
            set
            {
                if (!ReferenceEquals(_bANCO, value))
                {
                    var previousValue = _bANCO;
                    _bANCO = value;
                    FixupBANCO(previousValue);
                }
            }
        }
        private BANCO _bANCO;
    
        public virtual PROVEEDOR PROVEEDOR
        {
            get { return _pROVEEDOR; }
            set
            {
                if (!ReferenceEquals(_pROVEEDOR, value))
                {
                    var previousValue = _pROVEEDOR;
                    _pROVEEDOR = value;
                    FixupPROVEEDOR(previousValue);
                }
            }
        }
        private PROVEEDOR _pROVEEDOR;

        #endregion
        #region Association Fixup
    
        private void FixupBANCO(BANCO previousValue)
        {
            if (previousValue != null && previousValue.PROVEEDOR_CUENTA.Contains(this))
            {
                previousValue.PROVEEDOR_CUENTA.Remove(this);
            }
    
            if (BANCO != null)
            {
                if (!BANCO.PROVEEDOR_CUENTA.Contains(this))
                {
                    BANCO.PROVEEDOR_CUENTA.Add(this);
                }
                if (UNID_BANCO != BANCO.UNID_BANCO)
                {
                    UNID_BANCO = BANCO.UNID_BANCO;
                }
            }
        }
    
        private void FixupPROVEEDOR(PROVEEDOR previousValue)
        {
            if (previousValue != null && previousValue.PROVEEDOR_CUENTA.Contains(this))
            {
                previousValue.PROVEEDOR_CUENTA.Remove(this);
            }
    
            if (PROVEEDOR != null)
            {
                if (!PROVEEDOR.PROVEEDOR_CUENTA.Contains(this))
                {
                    PROVEEDOR.PROVEEDOR_CUENTA.Add(this);
                }
                if (UNID_PROVEEDOR != PROVEEDOR.UNID_PROVEEDOR)
                {
                    UNID_PROVEEDOR = PROVEEDOR.UNID_PROVEEDOR;
                }
            }
        }

        #endregion
    }
}
