//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class RECIBO_STATUS
    {
        #region Primitive Properties
    
        public virtual long UNID_RECIBO_STATUS
        {
            get;
            set;
        }
    
        public virtual string RECIBO_STATUS_NAME
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<RECIBO> RECIBOes
        {
            get
            {
                if (_rECIBOes == null)
                {
                    var newCollection = new FixupCollection<RECIBO>();
                    newCollection.CollectionChanged += FixupRECIBOes;
                    _rECIBOes = newCollection;
                }
                return _rECIBOes;
            }
            set
            {
                if (!ReferenceEquals(_rECIBOes, value))
                {
                    var previousValue = _rECIBOes as FixupCollection<RECIBO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRECIBOes;
                    }
                    _rECIBOes = value;
                    var newValue = value as FixupCollection<RECIBO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRECIBOes;
                    }
                }
            }
        }
        private ICollection<RECIBO> _rECIBOes;

        #endregion
        #region Association Fixup
    
        private void FixupRECIBOes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RECIBO item in e.NewItems)
                {
                    item.RECIBO_STATUS = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RECIBO item in e.OldItems)
                {
                    if (ReferenceEquals(item.RECIBO_STATUS, this))
                    {
                        item.RECIBO_STATUS = null;
                    }
                }
            }
        }

        #endregion
    }
}
