//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class STG_ITEM
    {
        #region Primitive Properties
    
        public virtual Nullable<long> UNID_ITEM
        {
            get;
            set;
        }
    
        public virtual string ARTICULO_NAME
        {
            get;
            set;
        }
    
        public virtual string EQUIPO_NAME
        {
            get;
            set;
        }
    
        public virtual string MODELO_NAME
        {
            get;
            set;
        }
    
        public virtual string MARCA_NAME
        {
            get;
            set;
        }
    
        public virtual string CATEGORIA_NAME
        {
            get;
            set;
        }
    
        public virtual long UNID_ARTICULO
        {
            get;
            set;
        }
    
        public virtual string SKU
        {
            get;
            set;
        }
    
        public virtual string NumeroSerie
        {
            get;
            set;
        }
    
        public virtual long UNID_ITEM_STATUS
        {
            get;
            set;
        }
    
        public virtual Nullable<double> CostoFinal
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_FACTURA_DETALLE
        {
            get;
            set;
        }
    
        public virtual Nullable<int> UNID_EMPRESA
        {
            get;
            set;
        }
    
        public virtual string STATUS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CANTIDAD
        {
            get;
            set;
        }
    
        public virtual long UNID_PROPIEDAD
        {
            get;
            set;
        }
    
        public virtual string Propiedad
        {
            get;
            set;
        }

        #endregion
    }
}
