//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class TRANSPORTE
    {
        #region Primitive Properties
    
        public virtual long UNID_TRANSPORTE
        {
            get;
            set;
        }
    
        public virtual string TRANSPORTE_NAME
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_TIPO_EMPRESA
        {
            get { return _uNID_TIPO_EMPRESA; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_TIPO_EMPRESA != value)
                    {
                        if (TIPO_EMPRESA != null && TIPO_EMPRESA.UNID_TIPO_EMPRESA != value)
                        {
                            TIPO_EMPRESA = null;
                        }
                        _uNID_TIPO_EMPRESA = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _uNID_TIPO_EMPRESA;
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual TIPO_EMPRESA TIPO_EMPRESA
        {
            get { return _tIPO_EMPRESA; }
            set
            {
                if (!ReferenceEquals(_tIPO_EMPRESA, value))
                {
                    var previousValue = _tIPO_EMPRESA;
                    _tIPO_EMPRESA = value;
                    FixupTIPO_EMPRESA(previousValue);
                }
            }
        }
        private TIPO_EMPRESA _tIPO_EMPRESA;
    
        public virtual ICollection<MOVIMENTO> MOVIMENTOes
        {
            get
            {
                if (_mOVIMENTOes == null)
                {
                    var newCollection = new FixupCollection<MOVIMENTO>();
                    newCollection.CollectionChanged += FixupMOVIMENTOes;
                    _mOVIMENTOes = newCollection;
                }
                return _mOVIMENTOes;
            }
            set
            {
                if (!ReferenceEquals(_mOVIMENTOes, value))
                {
                    var previousValue = _mOVIMENTOes as FixupCollection<MOVIMENTO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMOVIMENTOes;
                    }
                    _mOVIMENTOes = value;
                    var newValue = value as FixupCollection<MOVIMENTO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMOVIMENTOes;
                    }
                }
            }
        }
        private ICollection<MOVIMENTO> _mOVIMENTOes;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupTIPO_EMPRESA(TIPO_EMPRESA previousValue)
        {
            if (previousValue != null && previousValue.TRANSPORTEs.Contains(this))
            {
                previousValue.TRANSPORTEs.Remove(this);
            }
    
            if (TIPO_EMPRESA != null)
            {
                if (!TIPO_EMPRESA.TRANSPORTEs.Contains(this))
                {
                    TIPO_EMPRESA.TRANSPORTEs.Add(this);
                }
                if (UNID_TIPO_EMPRESA != TIPO_EMPRESA.UNID_TIPO_EMPRESA)
                {
                    UNID_TIPO_EMPRESA = TIPO_EMPRESA.UNID_TIPO_EMPRESA;
                }
            }
            else if (!_settingFK)
            {
                UNID_TIPO_EMPRESA = null;
            }
        }
    
        private void FixupMOVIMENTOes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MOVIMENTO item in e.NewItems)
                {
                    item.TRANSPORTE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MOVIMENTO item in e.OldItems)
                {
                    if (ReferenceEquals(item.TRANSPORTE, this))
                    {
                        item.TRANSPORTE = null;
                    }
                }
            }
        }

        #endregion
    }
}
