//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class UNIDAD
    {
        #region Primitive Properties
    
        public virtual long UNID_UNIDAD
        {
            get;
            set;
        }
    
        public virtual string UNIDAD1
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<FACTURA_DETALLE> FACTURA_DETALLE
        {
            get
            {
                if (_fACTURA_DETALLE == null)
                {
                    var newCollection = new FixupCollection<FACTURA_DETALLE>();
                    newCollection.CollectionChanged += FixupFACTURA_DETALLE;
                    _fACTURA_DETALLE = newCollection;
                }
                return _fACTURA_DETALLE;
            }
            set
            {
                if (!ReferenceEquals(_fACTURA_DETALLE, value))
                {
                    var previousValue = _fACTURA_DETALLE as FixupCollection<FACTURA_DETALLE>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFACTURA_DETALLE;
                    }
                    _fACTURA_DETALLE = value;
                    var newValue = value as FixupCollection<FACTURA_DETALLE>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFACTURA_DETALLE;
                    }
                }
            }
        }
        private ICollection<FACTURA_DETALLE> _fACTURA_DETALLE;

        #endregion
        #region Association Fixup
    
        private void FixupFACTURA_DETALLE(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (FACTURA_DETALLE item in e.NewItems)
                {
                    item.UNIDAD = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FACTURA_DETALLE item in e.OldItems)
                {
                    if (ReferenceEquals(item.UNIDAD, this))
                    {
                        item.UNIDAD = null;
                    }
                }
            }
        }

        #endregion
    }
}
