//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class USUARIO
    {
        #region Primitive Properties
    
        public virtual long UNID_USUARIO
        {
            get;
            set;
        }
    
        public virtual string USUARIO_MAIL
        {
            get;
            set;
        }
    
        public virtual string USUARIO_PWD
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<ROL> ROLs
        {
            get
            {
                if (_rOLs == null)
                {
                    var newCollection = new FixupCollection<ROL>();
                    newCollection.CollectionChanged += FixupROLs;
                    _rOLs = newCollection;
                }
                return _rOLs;
            }
            set
            {
                if (!ReferenceEquals(_rOLs, value))
                {
                    var previousValue = _rOLs as FixupCollection<ROL>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupROLs;
                    }
                    _rOLs = value;
                    var newValue = value as FixupCollection<ROL>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupROLs;
                    }
                }
            }
        }
        private ICollection<ROL> _rOLs;

        #endregion
        #region Association Fixup
    
        private void FixupROLs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ROL item in e.NewItems)
                {
                    if (!item.USUARIOs.Contains(this))
                    {
                        item.USUARIOs.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ROL item in e.OldItems)
                {
                    if (item.USUARIOs.Contains(this))
                    {
                        item.USUARIOs.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
