//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class INVENTARIO
    {
        #region Primitive Properties
    
        public virtual long UNID_INVENTARIO
        {
            get;
            set;
        }
    
        public virtual string DESCRIPTOR
        {
            get;
            set;
        }
    
        public virtual long UNID_SEGMENTO
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_ALMACEN
        {
            get { return _uNID_ALMACEN; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_ALMACEN != value)
                    {
                        if (ALMACEN != null && ALMACEN.UNID_ALMACEN != value)
                        {
                            ALMACEN = null;
                        }
                        _uNID_ALMACEN = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _uNID_ALMACEN;
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual System.DateTime FECHA
        {
            get;
            set;
        }
    
        public virtual bool FINISHED
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ALMACEN ALMACEN
        {
            get { return _aLMACEN; }
            set
            {
                if (!ReferenceEquals(_aLMACEN, value))
                {
                    var previousValue = _aLMACEN;
                    _aLMACEN = value;
                    FixupALMACEN(previousValue);
                }
            }
        }
        private ALMACEN _aLMACEN;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupALMACEN(ALMACEN previousValue)
        {
            if (previousValue != null && previousValue.INVENTARIOs.Contains(this))
            {
                previousValue.INVENTARIOs.Remove(this);
            }
    
            if (ALMACEN != null)
            {
                if (!ALMACEN.INVENTARIOs.Contains(this))
                {
                    ALMACEN.INVENTARIOs.Add(this);
                }
                if (UNID_ALMACEN != ALMACEN.UNID_ALMACEN)
                {
                    UNID_ALMACEN = ALMACEN.UNID_ALMACEN;
                }
            }
            else if (!_settingFK)
            {
                UNID_ALMACEN = null;
            }
        }

        #endregion
    }
}
