//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class ITEM
    {
        #region Primitive Properties
    
        public virtual long UNID_ITEM
        {
            get;
            set;
        }
    
        public virtual long UNID_ARTICULO
        {
            get { return _uNID_ARTICULO; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_ARTICULO != value)
                    {
                        if (ARTICULO != null && ARTICULO.UNID_ARTICULO != value)
                        {
                            ARTICULO = null;
                        }
                        _uNID_ARTICULO = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private long _uNID_ARTICULO;
    
        public virtual string SKU
        {
            get;
            set;
        }
    
        public virtual string NUMERO_SERIE
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_ITEM_STATUS
        {
            get { return _uNID_ITEM_STATUS; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_ITEM_STATUS != value)
                    {
                        if (ITEM_STATUS != null && ITEM_STATUS.UNID_ITEM_STATUS != value)
                        {
                            ITEM_STATUS = null;
                        }
                        _uNID_ITEM_STATUS = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _uNID_ITEM_STATUS;
    
        public virtual double COSTO_UNITARIO
        {
            get;
            set;
        }
    
        public virtual long UNID_FACTURA_DETALE
        {
            get { return _uNID_FACTURA_DETALE; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_FACTURA_DETALE != value)
                    {
                        if (FACTURA_DETALLE != null && FACTURA_DETALLE.UNID_FACTURA_DETALE != value)
                        {
                            FACTURA_DETALLE = null;
                        }
                        _uNID_FACTURA_DETALE = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private long _uNID_FACTURA_DETALE;
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_EMPRESA
        {
            get;
            set;
        }
    
        public virtual string STATUS
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }
    
        public virtual double PEDIMENTO_EXPO
        {
            get;
            set;
        }
    
        public virtual double PEDIMENTO_IMPO
        {
            get;
            set;
        }
    
        public virtual int CANTIDAD
        {
            get;
            set;
        }
    
        public virtual Nullable<long> UNID_PROPIEDAD
        {
            get { return _uNID_PROPIEDAD; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_PROPIEDAD != value)
                    {
                        if (PROPIEDAD != null && PROPIEDAD.UNID_PROPIEDAD != value)
                        {
                            PROPIEDAD = null;
                        }
                        _uNID_PROPIEDAD = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _uNID_PROPIEDAD;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<MASTER_INVENTARIOS> MASTER_INVENTARIOS
        {
            get
            {
                if (_mASTER_INVENTARIOS == null)
                {
                    var newCollection = new FixupCollection<MASTER_INVENTARIOS>();
                    newCollection.CollectionChanged += FixupMASTER_INVENTARIOS;
                    _mASTER_INVENTARIOS = newCollection;
                }
                return _mASTER_INVENTARIOS;
            }
            set
            {
                if (!ReferenceEquals(_mASTER_INVENTARIOS, value))
                {
                    var previousValue = _mASTER_INVENTARIOS as FixupCollection<MASTER_INVENTARIOS>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMASTER_INVENTARIOS;
                    }
                    _mASTER_INVENTARIOS = value;
                    var newValue = value as FixupCollection<MASTER_INVENTARIOS>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMASTER_INVENTARIOS;
                    }
                }
            }
        }
        private ICollection<MASTER_INVENTARIOS> _mASTER_INVENTARIOS;
    
        public virtual ICollection<MASTER_INVENTARIOS> MASTER_INVENTARIOS1
        {
            get
            {
                if (_mASTER_INVENTARIOS1 == null)
                {
                    var newCollection = new FixupCollection<MASTER_INVENTARIOS>();
                    newCollection.CollectionChanged += FixupMASTER_INVENTARIOS1;
                    _mASTER_INVENTARIOS1 = newCollection;
                }
                return _mASTER_INVENTARIOS1;
            }
            set
            {
                if (!ReferenceEquals(_mASTER_INVENTARIOS1, value))
                {
                    var previousValue = _mASTER_INVENTARIOS1 as FixupCollection<MASTER_INVENTARIOS>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMASTER_INVENTARIOS1;
                    }
                    _mASTER_INVENTARIOS1 = value;
                    var newValue = value as FixupCollection<MASTER_INVENTARIOS>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMASTER_INVENTARIOS1;
                    }
                }
            }
        }
        private ICollection<MASTER_INVENTARIOS> _mASTER_INVENTARIOS1;
    
        public virtual ARTICULO ARTICULO
        {
            get { return _aRTICULO; }
            set
            {
                if (!ReferenceEquals(_aRTICULO, value))
                {
                    var previousValue = _aRTICULO;
                    _aRTICULO = value;
                    FixupARTICULO(previousValue);
                }
            }
        }
        private ARTICULO _aRTICULO;
    
        public virtual ITEM_STATUS ITEM_STATUS
        {
            get { return _iTEM_STATUS; }
            set
            {
                if (!ReferenceEquals(_iTEM_STATUS, value))
                {
                    var previousValue = _iTEM_STATUS;
                    _iTEM_STATUS = value;
                    FixupITEM_STATUS(previousValue);
                }
            }
        }
        private ITEM_STATUS _iTEM_STATUS;
    
        public virtual PROPIEDAD PROPIEDAD
        {
            get { return _pROPIEDAD; }
            set
            {
                if (!ReferenceEquals(_pROPIEDAD, value))
                {
                    var previousValue = _pROPIEDAD;
                    _pROPIEDAD = value;
                    FixupPROPIEDAD(previousValue);
                }
            }
        }
        private PROPIEDAD _pROPIEDAD;
    
        public virtual ICollection<ULTIMO_MOVIMIENTO> ULTIMO_MOVIMIENTO
        {
            get
            {
                if (_uLTIMO_MOVIMIENTO == null)
                {
                    var newCollection = new FixupCollection<ULTIMO_MOVIMIENTO>();
                    newCollection.CollectionChanged += FixupULTIMO_MOVIMIENTO;
                    _uLTIMO_MOVIMIENTO = newCollection;
                }
                return _uLTIMO_MOVIMIENTO;
            }
            set
            {
                if (!ReferenceEquals(_uLTIMO_MOVIMIENTO, value))
                {
                    var previousValue = _uLTIMO_MOVIMIENTO as FixupCollection<ULTIMO_MOVIMIENTO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupULTIMO_MOVIMIENTO;
                    }
                    _uLTIMO_MOVIMIENTO = value;
                    var newValue = value as FixupCollection<ULTIMO_MOVIMIENTO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupULTIMO_MOVIMIENTO;
                    }
                }
            }
        }
        private ICollection<ULTIMO_MOVIMIENTO> _uLTIMO_MOVIMIENTO;
    
        public virtual ICollection<MOVIMIENTO_DETALLE> MOVIMIENTO_DETALLE
        {
            get
            {
                if (_mOVIMIENTO_DETALLE == null)
                {
                    var newCollection = new FixupCollection<MOVIMIENTO_DETALLE>();
                    newCollection.CollectionChanged += FixupMOVIMIENTO_DETALLE;
                    _mOVIMIENTO_DETALLE = newCollection;
                }
                return _mOVIMIENTO_DETALLE;
            }
            set
            {
                if (!ReferenceEquals(_mOVIMIENTO_DETALLE, value))
                {
                    var previousValue = _mOVIMIENTO_DETALLE as FixupCollection<MOVIMIENTO_DETALLE>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMOVIMIENTO_DETALLE;
                    }
                    _mOVIMIENTO_DETALLE = value;
                    var newValue = value as FixupCollection<MOVIMIENTO_DETALLE>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMOVIMIENTO_DETALLE;
                    }
                }
            }
        }
        private ICollection<MOVIMIENTO_DETALLE> _mOVIMIENTO_DETALLE;
    
        public virtual FACTURA_DETALLE FACTURA_DETALLE
        {
            get { return _fACTURA_DETALLE; }
            set
            {
                if (!ReferenceEquals(_fACTURA_DETALLE, value))
                {
                    var previousValue = _fACTURA_DETALLE;
                    _fACTURA_DETALLE = value;
                    FixupFACTURA_DETALLE(previousValue);
                }
            }
        }
        private FACTURA_DETALLE _fACTURA_DETALLE;
    
        public virtual ICollection<INVENTARIO_FISICO_DET> INVENTARIO_FISICO_DET
        {
            get
            {
                if (_iNVENTARIO_FISICO_DET == null)
                {
                    var newCollection = new FixupCollection<INVENTARIO_FISICO_DET>();
                    newCollection.CollectionChanged += FixupINVENTARIO_FISICO_DET;
                    _iNVENTARIO_FISICO_DET = newCollection;
                }
                return _iNVENTARIO_FISICO_DET;
            }
            set
            {
                if (!ReferenceEquals(_iNVENTARIO_FISICO_DET, value))
                {
                    var previousValue = _iNVENTARIO_FISICO_DET as FixupCollection<INVENTARIO_FISICO_DET>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupINVENTARIO_FISICO_DET;
                    }
                    _iNVENTARIO_FISICO_DET = value;
                    var newValue = value as FixupCollection<INVENTARIO_FISICO_DET>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupINVENTARIO_FISICO_DET;
                    }
                }
            }
        }
        private ICollection<INVENTARIO_FISICO_DET> _iNVENTARIO_FISICO_DET;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupARTICULO(ARTICULO previousValue)
        {
            if (previousValue != null && previousValue.ITEMs.Contains(this))
            {
                previousValue.ITEMs.Remove(this);
            }
    
            if (ARTICULO != null)
            {
                if (!ARTICULO.ITEMs.Contains(this))
                {
                    ARTICULO.ITEMs.Add(this);
                }
                if (UNID_ARTICULO != ARTICULO.UNID_ARTICULO)
                {
                    UNID_ARTICULO = ARTICULO.UNID_ARTICULO;
                }
            }
        }
    
        private void FixupITEM_STATUS(ITEM_STATUS previousValue)
        {
            if (previousValue != null && previousValue.ITEMs.Contains(this))
            {
                previousValue.ITEMs.Remove(this);
            }
    
            if (ITEM_STATUS != null)
            {
                if (!ITEM_STATUS.ITEMs.Contains(this))
                {
                    ITEM_STATUS.ITEMs.Add(this);
                }
                if (UNID_ITEM_STATUS != ITEM_STATUS.UNID_ITEM_STATUS)
                {
                    UNID_ITEM_STATUS = ITEM_STATUS.UNID_ITEM_STATUS;
                }
            }
            else if (!_settingFK)
            {
                UNID_ITEM_STATUS = null;
            }
        }
    
        private void FixupPROPIEDAD(PROPIEDAD previousValue)
        {
            if (previousValue != null && previousValue.ITEMs.Contains(this))
            {
                previousValue.ITEMs.Remove(this);
            }
    
            if (PROPIEDAD != null)
            {
                if (!PROPIEDAD.ITEMs.Contains(this))
                {
                    PROPIEDAD.ITEMs.Add(this);
                }
                if (UNID_PROPIEDAD != PROPIEDAD.UNID_PROPIEDAD)
                {
                    UNID_PROPIEDAD = PROPIEDAD.UNID_PROPIEDAD;
                }
            }
            else if (!_settingFK)
            {
                UNID_PROPIEDAD = null;
            }
        }
    
        private void FixupFACTURA_DETALLE(FACTURA_DETALLE previousValue)
        {
            if (previousValue != null && previousValue.ITEMs.Contains(this))
            {
                previousValue.ITEMs.Remove(this);
            }
    
            if (FACTURA_DETALLE != null)
            {
                if (!FACTURA_DETALLE.ITEMs.Contains(this))
                {
                    FACTURA_DETALLE.ITEMs.Add(this);
                }
                if (UNID_FACTURA_DETALE != FACTURA_DETALLE.UNID_FACTURA_DETALE)
                {
                    UNID_FACTURA_DETALE = FACTURA_DETALLE.UNID_FACTURA_DETALE;
                }
            }
        }
    
        private void FixupMASTER_INVENTARIOS(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MASTER_INVENTARIOS item in e.NewItems)
                {
                    item.ITEM = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MASTER_INVENTARIOS item in e.OldItems)
                {
                    if (ReferenceEquals(item.ITEM, this))
                    {
                        item.ITEM = null;
                    }
                }
            }
        }
    
        private void FixupMASTER_INVENTARIOS1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MASTER_INVENTARIOS item in e.NewItems)
                {
                    item.ITEM1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MASTER_INVENTARIOS item in e.OldItems)
                {
                    if (ReferenceEquals(item.ITEM1, this))
                    {
                        item.ITEM1 = null;
                    }
                }
            }
        }
    
        private void FixupULTIMO_MOVIMIENTO(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ULTIMO_MOVIMIENTO item in e.NewItems)
                {
                    item.ITEM = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ULTIMO_MOVIMIENTO item in e.OldItems)
                {
                    if (ReferenceEquals(item.ITEM, this))
                    {
                        item.ITEM = null;
                    }
                }
            }
        }
    
        private void FixupMOVIMIENTO_DETALLE(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MOVIMIENTO_DETALLE item in e.NewItems)
                {
                    item.ITEM = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MOVIMIENTO_DETALLE item in e.OldItems)
                {
                    if (ReferenceEquals(item.ITEM, this))
                    {
                        item.ITEM = null;
                    }
                }
            }
        }
    
        private void FixupINVENTARIO_FISICO_DET(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (INVENTARIO_FISICO_DET item in e.NewItems)
                {
                    item.ITEM = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (INVENTARIO_FISICO_DET item in e.OldItems)
                {
                    if (ReferenceEquals(item.ITEM, this))
                    {
                        item.ITEM = null;
                    }
                }
            }
        }

        #endregion
    }
}
