//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class INVENTARIO_FISICO_DET
    {
        #region Primitive Properties
    
        public virtual long UNID_INVENTARIO_FISICO_DET
        {
            get;
            set;
        }
    
        public virtual long UNID_INVENTARIO_FISICO
        {
            get { return _uNID_INVENTARIO_FISICO; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_INVENTARIO_FISICO != value)
                    {
                        if (INVENTARIO_FISICO != null && INVENTARIO_FISICO.UNID_INVENTARIO_FISICO != value)
                        {
                            INVENTARIO_FISICO = null;
                        }
                        _uNID_INVENTARIO_FISICO = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private long _uNID_INVENTARIO_FISICO;
    
        public virtual Nullable<long> UNID_ITEM
        {
            get { return _uNID_ITEM; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uNID_ITEM != value)
                    {
                        if (ITEM != null && ITEM.UNID_ITEM != value)
                        {
                            ITEM = null;
                        }
                        _uNID_ITEM = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _uNID_ITEM;
    
        public virtual string SKU
        {
            get;
            set;
        }
    
        public virtual string NUMERO_SERIE
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CANTIDAD
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual Nullable<long> LAST_MODIFIED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual INVENTARIO_FISICO INVENTARIO_FISICO
        {
            get { return _iNVENTARIO_FISICO; }
            set
            {
                if (!ReferenceEquals(_iNVENTARIO_FISICO, value))
                {
                    var previousValue = _iNVENTARIO_FISICO;
                    _iNVENTARIO_FISICO = value;
                    FixupINVENTARIO_FISICO(previousValue);
                }
            }
        }
        private INVENTARIO_FISICO _iNVENTARIO_FISICO;
    
        public virtual ITEM ITEM
        {
            get { return _iTEM; }
            set
            {
                if (!ReferenceEquals(_iTEM, value))
                {
                    var previousValue = _iTEM;
                    _iTEM = value;
                    FixupITEM(previousValue);
                }
            }
        }
        private ITEM _iTEM;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupINVENTARIO_FISICO(INVENTARIO_FISICO previousValue)
        {
            if (previousValue != null && previousValue.INVENTARIO_FISICO_DET.Contains(this))
            {
                previousValue.INVENTARIO_FISICO_DET.Remove(this);
            }
    
            if (INVENTARIO_FISICO != null)
            {
                if (!INVENTARIO_FISICO.INVENTARIO_FISICO_DET.Contains(this))
                {
                    INVENTARIO_FISICO.INVENTARIO_FISICO_DET.Add(this);
                }
                if (UNID_INVENTARIO_FISICO != INVENTARIO_FISICO.UNID_INVENTARIO_FISICO)
                {
                    UNID_INVENTARIO_FISICO = INVENTARIO_FISICO.UNID_INVENTARIO_FISICO;
                }
            }
        }
    
        private void FixupITEM(ITEM previousValue)
        {
            if (previousValue != null && previousValue.INVENTARIO_FISICO_DET.Contains(this))
            {
                previousValue.INVENTARIO_FISICO_DET.Remove(this);
            }
    
            if (ITEM != null)
            {
                if (!ITEM.INVENTARIO_FISICO_DET.Contains(this))
                {
                    ITEM.INVENTARIO_FISICO_DET.Add(this);
                }
                if (UNID_ITEM != ITEM.UNID_ITEM)
                {
                    UNID_ITEM = ITEM.UNID_ITEM;
                }
            }
            else if (!_settingFK)
            {
                UNID_ITEM = null;
            }
        }

        #endregion
    }
}
