//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InventoryApp.DAL.POCOS
{
    public partial class PEDIMENTO
    {
        #region Primitive Properties
    
        public virtual long UNID_PEDIMENTO
        {
            get;
            set;
        }
    
        public virtual long UNID_LOTE
        {
            get { return _uNID_LOTE; }
            set
            {
                if (_uNID_LOTE != value)
                {
                    if (LOTE != null && LOTE.UNID_LOTE != value)
                    {
                        LOTE = null;
                    }
                    _uNID_LOTE = value;
                }
            }
        }
        private long _uNID_LOTE;
    
        public virtual long UNID_TIPO_PEDIMENTO
        {
            get { return _uNID_TIPO_PEDIMENTO; }
            set
            {
                if (_uNID_TIPO_PEDIMENTO != value)
                {
                    if (TIPO_PEDIMENTO != null && TIPO_PEDIMENTO.UNID_TIPO_PEDIMENTO != value)
                    {
                        TIPO_PEDIMENTO = null;
                    }
                    _uNID_TIPO_PEDIMENTO = value;
                }
            }
        }
        private long _uNID_TIPO_PEDIMENTO;
    
        public virtual string PEDIMENTO_NUMERO
        {
            get;
            set;
        }
    
        public virtual bool IS_ACTIVE
        {
            get;
            set;
        }
    
        public virtual bool IS_MODIFIED
        {
            get;
            set;
        }
    
        public virtual long LAST_MODIFIED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<MASTER_INVENTARIOS> MASTER_INVENTARIOS
        {
            get
            {
                if (_mASTER_INVENTARIOS == null)
                {
                    var newCollection = new FixupCollection<MASTER_INVENTARIOS>();
                    newCollection.CollectionChanged += FixupMASTER_INVENTARIOS;
                    _mASTER_INVENTARIOS = newCollection;
                }
                return _mASTER_INVENTARIOS;
            }
            set
            {
                if (!ReferenceEquals(_mASTER_INVENTARIOS, value))
                {
                    var previousValue = _mASTER_INVENTARIOS as FixupCollection<MASTER_INVENTARIOS>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMASTER_INVENTARIOS;
                    }
                    _mASTER_INVENTARIOS = value;
                    var newValue = value as FixupCollection<MASTER_INVENTARIOS>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMASTER_INVENTARIOS;
                    }
                }
            }
        }
        private ICollection<MASTER_INVENTARIOS> _mASTER_INVENTARIOS;
    
        public virtual TIPO_PEDIMENTO TIPO_PEDIMENTO
        {
            get { return _tIPO_PEDIMENTO; }
            set
            {
                if (!ReferenceEquals(_tIPO_PEDIMENTO, value))
                {
                    var previousValue = _tIPO_PEDIMENTO;
                    _tIPO_PEDIMENTO = value;
                    FixupTIPO_PEDIMENTO(previousValue);
                }
            }
        }
        private TIPO_PEDIMENTO _tIPO_PEDIMENTO;
    
        public virtual ICollection<FACTURA_DETALLE> FACTURA_DETALLE
        {
            get
            {
                if (_fACTURA_DETALLE == null)
                {
                    var newCollection = new FixupCollection<FACTURA_DETALLE>();
                    newCollection.CollectionChanged += FixupFACTURA_DETALLE;
                    _fACTURA_DETALLE = newCollection;
                }
                return _fACTURA_DETALLE;
            }
            set
            {
                if (!ReferenceEquals(_fACTURA_DETALLE, value))
                {
                    var previousValue = _fACTURA_DETALLE as FixupCollection<FACTURA_DETALLE>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFACTURA_DETALLE;
                    }
                    _fACTURA_DETALLE = value;
                    var newValue = value as FixupCollection<FACTURA_DETALLE>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFACTURA_DETALLE;
                    }
                }
            }
        }
        private ICollection<FACTURA_DETALLE> _fACTURA_DETALLE;
    
        public virtual LOTE LOTE
        {
            get { return _lOTE; }
            set
            {
                if (!ReferenceEquals(_lOTE, value))
                {
                    var previousValue = _lOTE;
                    _lOTE = value;
                    FixupLOTE(previousValue);
                }
            }
        }
        private LOTE _lOTE;

        #endregion
        #region Association Fixup
    
        private void FixupTIPO_PEDIMENTO(TIPO_PEDIMENTO previousValue)
        {
            if (previousValue != null && previousValue.PEDIMENTOes.Contains(this))
            {
                previousValue.PEDIMENTOes.Remove(this);
            }
    
            if (TIPO_PEDIMENTO != null)
            {
                if (!TIPO_PEDIMENTO.PEDIMENTOes.Contains(this))
                {
                    TIPO_PEDIMENTO.PEDIMENTOes.Add(this);
                }
                if (UNID_TIPO_PEDIMENTO != TIPO_PEDIMENTO.UNID_TIPO_PEDIMENTO)
                {
                    UNID_TIPO_PEDIMENTO = TIPO_PEDIMENTO.UNID_TIPO_PEDIMENTO;
                }
            }
        }
    
        private void FixupLOTE(LOTE previousValue)
        {
            if (previousValue != null && previousValue.PEDIMENTOes.Contains(this))
            {
                previousValue.PEDIMENTOes.Remove(this);
            }
    
            if (LOTE != null)
            {
                if (!LOTE.PEDIMENTOes.Contains(this))
                {
                    LOTE.PEDIMENTOes.Add(this);
                }
                if (UNID_LOTE != LOTE.UNID_LOTE)
                {
                    UNID_LOTE = LOTE.UNID_LOTE;
                }
            }
        }
    
        private void FixupMASTER_INVENTARIOS(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MASTER_INVENTARIOS item in e.NewItems)
                {
                    item.PEDIMENTO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MASTER_INVENTARIOS item in e.OldItems)
                {
                    if (ReferenceEquals(item.PEDIMENTO, this))
                    {
                        item.PEDIMENTO = null;
                    }
                }
            }
        }
    
        private void FixupFACTURA_DETALLE(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (FACTURA_DETALLE item in e.NewItems)
                {
                    item.PEDIMENTO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FACTURA_DETALLE item in e.OldItems)
                {
                    if (ReferenceEquals(item.PEDIMENTO, this))
                    {
                        item.PEDIMENTO = null;
                    }
                }
            }
        }

        #endregion
    }
}
